BOARD_USES_MSM7X27_RECOVERY := true

TARGET_RECOVERY_INITRC = device/htc/msm7x27-common/recovery/init.htc.rc

#BOARD_USES_RECOVERY_CHARGEMODE := true
BOARD_USES_MMCUTILS := false

#BOARD_CUSTOM_GRAPHICS := ../../../device/htc/msm7x27-common/recovery/graphics.c

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_NO_MISC_PARTITION := true

DEVICE_RESOLUTION := 320x480
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
BOARD_HAS_NO_REAL_SDCARD := true
BOARD_HAS_LOW_RESOLUTION := true

TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true
